"""Initial migration for SQLite

Revision ID: 45c03a6e2e33
Revises: 
Create Date: 2023-08-22 23:01:24.578315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c03a6e2e33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_type', sa.String(length=1), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('money', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('living_area', sa.Integer(), nullable=True),
    sa.Column('kitchen_area', sa.Integer(), nullable=True),
    sa.Column('nfloor', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('holder', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('prepay', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('insurance', sa.Integer(), nullable=True),
    sa.Column('rental_period', sa.Integer(), nullable=True),
    sa.Column('contract_type', sa.Integer(), nullable=True),
    sa.Column('client_commission', sa.Integer(), nullable=True),
    sa.Column('agents', sa.Boolean(), nullable=True),
    sa.Column('agents_commission', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('metro', sa.Integer(), nullable=True),
    sa.Column('metro_dist', sa.Integer(), nullable=True),
    sa.Column('walk', sa.Boolean(), nullable=True),
    sa.Column('railway_dist', sa.Integer(), nullable=True),
    sa.Column('kitchen_furn', sa.Boolean(), nullable=True),
    sa.Column('room_furn', sa.Boolean(), nullable=True),
    sa.Column('refrigerator', sa.Boolean(), nullable=True),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.Column('washing_automat', sa.Boolean(), nullable=True),
    sa.Column('dishwasher', sa.Boolean(), nullable=True),
    sa.Column('internet', sa.Boolean(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.Column('windows', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('bath', sa.Boolean(), nullable=True),
    sa.Column('shower_cab', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('repair_need', sa.Integer(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['holder'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('living_area', sa.Integer(), nullable=True),
    sa.Column('kitchen_area', sa.Integer(), nullable=True),
    sa.Column('nfloor', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=6, asdecimal=2), nullable=True),
    sa.Column('agents', sa.Boolean(), nullable=True),
    sa.Column('agents_commission', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('metro', sa.Integer(), nullable=True),
    sa.Column('metro_dist', sa.Integer(), nullable=True),
    sa.Column('walk', sa.Boolean(), nullable=True),
    sa.Column('railway_dist', sa.Integer(), nullable=True),
    sa.Column('kitchen_furn', sa.Boolean(), nullable=True),
    sa.Column('room_furn', sa.Boolean(), nullable=True),
    sa.Column('refrigerator', sa.Boolean(), nullable=True),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.Column('washing_automat', sa.Boolean(), nullable=True),
    sa.Column('dishwasher', sa.Boolean(), nullable=True),
    sa.Column('internet', sa.Boolean(), nullable=True),
    sa.Column('columnes', sa.Integer(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.Column('windows', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('bath', sa.Boolean(), nullable=True),
    sa.Column('shower_cab', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('repair_need', sa.Integer(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('house')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
