"""return to PostgreSQL

Revision ID: ab6bf3840dae
Revises: f3c8de56dc16
Create Date: 2023-09-10 01:14:14.407784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6bf3840dae'
down_revision = 'f3c8de56dc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('prepay',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6, asdecimal=2),
               existing_nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6, asdecimal=2),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               existing_nullable=True,
               existing_server_default=sa.text("'1'::bpchar"))
        batch_op.alter_column('money',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
        batch_op.drop_column('agency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('money',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               existing_nullable=True,
               existing_server_default=sa.text("'1'::bpchar"))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=6, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('prepay',
               existing_type=sa.Float(precision=6, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=6, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
