"""PostgreSQL auth, house, purchase

Revision ID: f3c8de56dc16
Revises: 
Create Date: 2023-05-17 00:12:42.687652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c8de56dc16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6, asdecimal=2),
               existing_nullable=True)
        batch_op.alter_column('prepay',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6, asdecimal=2),
               existing_nullable=True)
        batch_op.drop_column('columnes')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6, asdecimal=2),
               existing_nullable=True)
        batch_op.drop_column('rental_period')
        batch_op.drop_column('insurance')
        batch_op.drop_column('prepay')
        batch_op.drop_column('client_commission')
        batch_op.drop_column('contract_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('money',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('money',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_type', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client_commission', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prepay', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('insurance', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rental_period', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=6, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columnes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('prepay',
               existing_type=sa.Float(precision=6, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=6, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
